
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "demo-2.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "demo-2.fullname" . }}

